import{useState}from"react";import{Sparkles,Leaf,CloudSun,Droplets,Bug,Menu,X}from"lucide-react";import{Sidebar}from"./components/Sidebar";import{ChatComposer}from"./components/ChatComposer";import{MessageBubble}from"./components/MessageBubble";import{sendChat}from"./lib/api";import type{ChatResponse}from"./types/chat";import"./styles.css";
const prompts=[{icon:Leaf,text:"What crop is suitable for this season in Karnataka?"},{icon:Droplets,text:"How can I reduce water use in vegetable cultivation?"},{icon:Bug,text:"What should I check if my tomato leaves are curling?"},{icon:CloudSun,text:"What information do you need for weather-aware farming?"}];
export default function App(){
 const[messages,setMessages]=useState<{text:string;result?:ChatResponse}[]>([]);const[loading,setLoading]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);
 const ask=async(text:string)=>{setMessages(p=>[...p,{text}]);setLoading(true);try{const result=await sendChat({message:text,language:"auto"});setMessages(p=>[...p,{text:"",result}])}catch(e){setMessages(p=>[...p,{text:"",result:{answer:e instanceof Error?e.message:"Something went wrong.",assessment:"",recommended_actions:[],what_to_monitor:[],limitations:["Check that the FastAPI backend is running and IBM watsonx.ai credentials are configured."],sources:[],live_data_available:false,model:"unavailable",retrieval_used:false}}])}finally{setLoading(false)}};
 return <div className="app-shell"><button className="mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?<X/>:<Menu/>}</button><div className={mobileOpen?"sidebar-mobile open":"sidebar-mobile"}><Sidebar/></div><Sidebar/><main className="main">
  <header className="topbar"><div><div className="eyebrow"><Sparkles size={14}/> IBM Granite · Retrieval-Augmented Generation</div><h1>Your farming decisions, grounded in knowledge.</h1></div><div className="status"><span className="dot"/> RAG Assistant</div></header>
  {messages.length===0?<section className="hero"><div className="hero-badge"><Leaf size={16}/> Agriculture AI</div><h2>Ask KrishiNiti AI.</h2><p>Get practical, context-aware farming guidance grounded in a curated agricultural knowledge base.</p><div className="prompt-grid">{prompts.map(({icon:Icon,text})=><button key={text} onClick={()=>ask(text)}><Icon size={19}/><span>{text}</span></button>)}</div><div className="feature-row"><div><strong>RAG</strong><span>Semantic retrieval</span></div><div><strong>Granite</strong><span>IBM reasoning model</span></div><div><strong>3 languages</strong><span>English · Kannada · Hindi</span></div><div><strong>Grounded</strong><span>No fabricated live data</span></div></div></section>:<section className="chat-area">{messages.map((m,i)=>m.result?<MessageBubble key={i} message="" result={m.result}/>:<MessageBubble key={i} message={m.text}/>)}{loading&&<div className="typing"><span/><span/><span/> KrishiNiti AI is retrieving relevant knowledge…</div>}</section>}
  <div className="composer-area"><ChatComposer onSend={ask} loading={loading}/></div><footer>KrishiNiti AI · General agricultural guidance, not a substitute for qualified local advice.</footer>
 </main></div>
}
